name: ltemanager2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  clay_containers: ^0.3.2
  crypto: ^3.0.1
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  # flutter_native_admob: ^2.1.0+3
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  http: ^0.13.4
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  kt_dart: ^0.10.0
  logger: ^1.1.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  xml2json: ^5.3.2
  salomon_bottom_bar: ^3.2.0
  glass_kit: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/ltemanagerLogo.png"

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: null
  chopper_generator: null
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  lint: ^1.1.1


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/logo/
    - assets/background/
